### PR TITLE
Sort list of files when building mimeo--$EXTVERSION.sql

### PR DESCRIPTION
**Pull request by ChristophBerg**
The ordering would otherwise be in filesystem order, which can vary
between builds and produce different results.

Spotted by Debian's reproducible builds project, see
https://reproducible.debian.net/dbd/unstable/armhf/mimeo_1.3.9-1.diffoscope.html

### CODE REVIEW

**Comment by keithf4** [comment]
It may not be the case at the moment, but I split things out into folders like I did because some objects have to be created before others. Like the functions have to be made before the triggers can. 

I do like the idea of sorting them, though. I changed the Makefile for the next version to do this instead
```
sql/$(EXTENSION)--$(EXTVERSION).sql: $(sort sql/tables/*.sql) $(sort sql/functions/*.sql) $(sort sql/triggers/*.sql)
```
Thanks for the idea!

**Comment by ChristophBerg** [comment]
Hi Keith,

sorry I submitted the patch too soon - unfortunately it doesn't fix the problem at all. The * globs were expanded by the shell instead of in make, so all the $(sort) did was to sort the list of patterns. I've updated the pull request to correctly call $(sort $(wildcard ...)) on all three directories separately.

Happy New Year,
Christoph

**Comment by ChristophBerg** [comment]
Fwiw, the same reproducibility issue is present in pg_partman's Makefile as well.

**Comment by keithf4** [comment]
Thanks for the fix. I'm still not all that well versed in Makefiles.
I plan on applying this to all my extensions. Thanks!

**Comment by keithf4** [comment]
This fix has been included in v1.4.0
Thanks!

**Pull request closed without merging**
